CREATE TABLE IF NOT EXISTS app_settings (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  commission_level_1 DECIMAL(5, 4) NOT NULL DEFAULT 0.1200,
  commission_level_2 DECIMAL(5, 4) NOT NULL DEFAULT 0.0500,
  min_withdrawal DECIMAL(10, 2) NOT NULL DEFAULT 10.00,
  compliance_name VARCHAR(20) NOT NULL DEFAULT '推荐有礼',
  auto_pay_enabled TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_app_settings_appid (appid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(160) NOT NULL,
  status ENUM('active','disabled') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_admin_users_username (username),
  KEY idx_admin_users_appid (appid, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  openid VARCHAR(96) NOT NULL,
  phone VARCHAR(32) NOT NULL DEFAULT '',
  nickname VARCHAR(64) NOT NULL,
  avatar VARCHAR(255) NOT NULL DEFAULT '',
  parent_id BIGINT UNSIGNED NULL,
  first_parent_id BIGINT UNSIGNED NULL,
  distributor_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  session_token CHAR(64) NULL,
  session_key_cipher VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_users_appid_openid (appid, openid),
  UNIQUE KEY uk_users_session_token (session_token),
  KEY idx_users_appid_created (appid, created_at),
  KEY idx_users_parent (parent_id),
  KEY idx_users_first_parent (first_parent_id),
  KEY idx_users_distributor_status (distributor_status),
  CONSTRAINT fk_users_parent FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_users_first_parent FOREIGN KEY (first_parent_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_addresses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  user_id BIGINT UNSIGNED NOT NULL,
  receiver_name VARCHAR(64) NOT NULL DEFAULT '',
  phone VARCHAR(32) NOT NULL DEFAULT '',
  province VARCHAR(64) NOT NULL DEFAULT '',
  city VARCHAR(64) NOT NULL DEFAULT '',
  district VARCHAR(64) NOT NULL DEFAULT '',
  detail VARCHAR(180) NOT NULL DEFAULT '',
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_user_addresses_app_user_default (appid, user_id, is_default, id),
  KEY idx_user_addresses_user_default (user_id, is_default, id),
  CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  title VARCHAR(160) NOT NULL,
  subtitle VARCHAR(255) NOT NULL DEFAULT '',
  product_no VARCHAR(64) NOT NULL DEFAULT '',
  barcode VARCHAR(64) NOT NULL DEFAULT '',
  category VARCHAR(64) NOT NULL DEFAULT '未分类',
  brand VARCHAR(64) NOT NULL DEFAULT '',
  unit VARCHAR(16) NOT NULL DEFAULT '件',
  market_price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  price DECIMAL(10, 2) NOT NULL,
  cost_price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  stock INT UNSIGNED NOT NULL DEFAULT 0,
  sales INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('on','off') NOT NULL DEFAULT 'on',
  commission_rate DECIMAL(5, 4) NOT NULL DEFAULT 0.1200,
  image_url VARCHAR(600) NOT NULL DEFAULT '',
  images_json JSON NULL,
  detail_html MEDIUMTEXT NULL,
  description TEXT,
  weight DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  min_buy_qty INT UNSIGNED NOT NULL DEFAULT 1,
  per_order_limit INT UNSIGNED NOT NULL DEFAULT 0,
  per_user_limit INT UNSIGNED NOT NULL DEFAULT 0,
  is_virtual TINYINT(1) NOT NULL DEFAULT 0,
  no_refund_after_pay TINYINT(1) NOT NULL DEFAULT 0,
  freight_template VARCHAR(80) NOT NULL DEFAULT '',
  delivery_methods JSON NULL,
  vip_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_products_no (product_no),
  KEY idx_products_barcode (barcode),
  KEY idx_products_app_status_category (appid, status, category),
  KEY idx_products_status_category (status, category),
  KEY idx_products_sales (sales),
  FULLTEXT KEY ft_products_title_desc (title, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS acquisition_campaigns (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  name VARCHAR(160) NOT NULL,
  description VARCHAR(255) NOT NULL DEFAULT '',
  product_id BIGINT UNSIGNED NOT NULL,
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP NOT NULL,
  hide_time TINYINT(1) NOT NULL DEFAULT 0,
  stock INT UNSIGNED NOT NULL DEFAULT 0,
  sold_count INT UNSIGNED NOT NULL DEFAULT 0,
  lead_price DECIMAL(10, 2) NOT NULL,
  settle_price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  per_user_limit INT UNSIGNED NOT NULL DEFAULT 0,
  per_order_limit INT UNSIGNED NOT NULL DEFAULT 0,
  delivery_methods JSON NULL,
  free_shipping TINYINT(1) NOT NULL DEFAULT 1,
  show_store_address TINYINT(1) NOT NULL DEFAULT 0,
  verify_at_order_store TINYINT(1) NOT NULL DEFAULT 0,
  member_tag VARCHAR(64) NOT NULL DEFAULT '',
  post_pay_address TINYINT(1) NOT NULL DEFAULT 0,
  relation_mode ENUM('current','first','activity_visit','activity_paid') NOT NULL DEFAULT 'activity_paid',
  default_inviter_id BIGINT UNSIGNED NULL,
  reward_issue_way ENUM('withdraw','instant') NOT NULL DEFAULT 'withdraw',
  reward_permission ENUM('all','buyer_only') NOT NULL DEFAULT 'all',
  reward_rule ENUM('uniform','member_level') NOT NULL DEFAULT 'uniform',
  reward_level1 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  reward_level2 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  direct_pay_way ENUM('wechat_balance') NOT NULL DEFAULT 'wechat_balance',
  reward_multiple_enabled TINYINT(1) NOT NULL DEFAULT 0,
  reward_step_enabled TINYINT(1) NOT NULL DEFAULT 0,
  team_reward_enabled TINYINT(1) NOT NULL DEFAULT 0,
  team_reward_level1 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  team_reward_level2 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  lottery_enabled TINYINT(1) NOT NULL DEFAULT 0,
  lottery_config JSON NULL,
  qrcode_guide_image VARCHAR(600) NOT NULL DEFAULT '',
  team_qrcode_enabled TINYINT(1) NOT NULL DEFAULT 0,
  team_qrcode_types JSON NULL,
  traffic_config JSON NULL,
  share_cover VARCHAR(600) NOT NULL DEFAULT '',
  share_description VARCHAR(255) NOT NULL DEFAULT '',
  share_timeline_text VARCHAR(255) NOT NULL DEFAULT '',
  customer_service_qrcode VARCHAR(600) NOT NULL DEFAULT '',
  background_music VARCHAR(600) NOT NULL DEFAULT '',
  poster_config JSON NULL,
  form_schema JSON NULL,
  virtual_sold_count INT UNSIGNED NOT NULL DEFAULT 0,
  virtual_share_count INT UNSIGNED NOT NULL DEFAULT 0,
  virtual_browse_count INT UNSIGNED NOT NULL DEFAULT 0,
  virtual_invite_count INT UNSIGNED NOT NULL DEFAULT 0,
  virtual_rankings JSON NULL,
  status ENUM('draft','published','ended','expired') NOT NULL DEFAULT 'draft',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_acquisition_status_time (status, start_at, end_at),
  KEY idx_acquisition_app_status_time (appid, status, start_at, end_at),
  KEY idx_acquisition_product (product_id),
  KEY idx_acquisition_default_inviter (default_inviter_id),
  CONSTRAINT fk_acquisition_product FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT fk_acquisition_default_inviter FOREIGN KEY (default_inviter_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS acquisition_qrcodes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  campaign_id BIGINT UNSIGNED NOT NULL,
  type ENUM('personal','group') NOT NULL,
  name VARCHAR(80) NOT NULL,
  image_url VARCHAR(600) NOT NULL DEFAULT '',
  poster_bg VARCHAR(600) NOT NULL DEFAULT '',
  poster_position JSON NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  show_limit INT UNSIGNED NOT NULL DEFAULT 0,
  shown_count INT UNSIGNED NOT NULL DEFAULT 0,
  is_default_template TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('enabled','disabled') NOT NULL DEFAULT 'enabled',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_qrcodes_campaign_type (campaign_id, type, status),
  CONSTRAINT fk_qrcodes_campaign FOREIGN KEY (campaign_id) REFERENCES acquisition_campaigns(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS acquisition_relations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  campaign_id BIGINT UNSIGNED NOT NULL,
  member_id BIGINT UNSIGNED NOT NULL,
  inviter_id BIGINT UNSIGNED NULL,
  parent_inviter_id BIGINT UNSIGNED NULL,
  team_leader_id BIGINT UNSIGNED NULL,
  indirect_team_leader_id BIGINT UNSIGNED NULL,
  locked_by ENUM('system','visit','paid','manual') NOT NULL DEFAULT 'system',
  entered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  unlocked_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_campaign_member (appid, campaign_id, member_id),
  KEY idx_relations_inviter (appid, campaign_id, inviter_id),
  KEY idx_relations_parent (appid, campaign_id, parent_inviter_id),
  CONSTRAINT fk_relations_campaign FOREIGN KEY (campaign_id) REFERENCES acquisition_campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_relations_member FOREIGN KEY (member_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_relations_inviter FOREIGN KEY (inviter_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_relations_parent FOREIGN KEY (parent_inviter_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_relations_team FOREIGN KEY (team_leader_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_relations_indirect_team FOREIGN KEY (indirect_team_leader_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS screen_heartbeats (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  user_id BIGINT UNSIGNED NOT NULL,
  campaign_id BIGINT UNSIGNED NULL,
  product_id BIGINT UNSIGNED NULL,
  scene VARCHAR(64) NOT NULL DEFAULT '',
  page VARCHAR(40) NOT NULL DEFAULT '',
  session_key VARCHAR(96) NOT NULL,
  last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_screen_heartbeat_session (appid, session_key),
  KEY idx_screen_heartbeat_seen (appid, last_seen_at),
  KEY idx_screen_heartbeat_campaign_seen (appid, campaign_id, last_seen_at),
  KEY idx_screen_heartbeat_product_seen (appid, product_id, last_seen_at),
  CONSTRAINT fk_screen_heartbeat_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_screen_heartbeat_campaign FOREIGN KEY (campaign_id) REFERENCES acquisition_campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_screen_heartbeat_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS acquisition_materials (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  type ENUM('qrcode_bg','share_poster','share_cover') NOT NULL,
  image_url VARCHAR(600) NOT NULL,
  style_config JSON NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_materials_app_type_sort (appid, type, sort_order, id),
  KEY idx_materials_type_sort (type, sort_order, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  status ENUM('unpaid','paid','shipped','received','refunded','closed') NOT NULL DEFAULT 'unpaid',
  pay_provider VARCHAR(32) NOT NULL DEFAULT '',
  out_trade_no VARCHAR(64) NULL,
  transaction_id VARCHAR(64) NOT NULL DEFAULT '',
  prepay_id VARCHAR(128) NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL DEFAULT '',
  address_id BIGINT UNSIGNED NULL,
  logistics_no VARCHAR(80) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  received_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_orders_out_trade_no (out_trade_no),
  KEY idx_orders_transaction (transaction_id),
  KEY idx_orders_app_user_created (appid, user_id, created_at),
  KEY idx_orders_app_status_created (appid, status, created_at),
  KEY idx_orders_user_created (user_id, created_at),
  KEY idx_orders_status_created (status, created_at),
  KEY idx_orders_product (product_id),
  KEY idx_orders_address (address_id),
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_orders_product FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT fk_orders_address FOREIGN KEY (address_id) REFERENCES user_addresses(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS acquisition_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  campaign_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  inviter_id BIGINT UNSIGNED NULL,
  parent_inviter_id BIGINT UNSIGNED NULL,
  team_leader_id BIGINT UNSIGNED NULL,
  indirect_team_leader_id BIGINT UNSIGNED NULL,
  form_values JSON NULL,
  scene VARCHAR(64) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_acquisition_order (order_id),
  KEY idx_acquisition_orders_campaign (appid, campaign_id, created_at),
  KEY idx_acquisition_orders_inviter (appid, campaign_id, inviter_id),
  CONSTRAINT fk_acq_orders_campaign FOREIGN KEY (campaign_id) REFERENCES acquisition_campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_acq_orders_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_acq_orders_inviter FOREIGN KEY (inviter_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_acq_orders_parent FOREIGN KEY (parent_inviter_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_acq_orders_team FOREIGN KEY (team_leader_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_acq_orders_indirect_team FOREIGN KEY (indirect_team_leader_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS acquisition_lottery_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  campaign_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  prize_name VARCHAR(120) NOT NULL DEFAULT '',
  prize_type ENUM('thanks','cash','goods','coupon') NOT NULL DEFAULT 'thanks',
  prize_image VARCHAR(600) NOT NULL DEFAULT '',
  quantity INT UNSIGNED NOT NULL DEFAULT 0,
  amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  status ENUM('pending','issued','failed') NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_lottery_campaign_created (appid, campaign_id, created_at),
  KEY idx_lottery_user (appid, user_id, created_at),
  CONSTRAINT fk_lottery_campaign FOREIGN KEY (campaign_id) REFERENCES acquisition_campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_lottery_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_lottery_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS commissions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  order_id BIGINT UNSIGNED NOT NULL,
  beneficiary_id BIGINT UNSIGNED NOT NULL,
  buyer_id BIGINT UNSIGNED NOT NULL,
  level TINYINT UNSIGNED NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  status ENUM('pending','withdrawable','canceled') NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  available_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_commissions_order_beneficiary_level (order_id, beneficiary_id, level),
  KEY idx_commissions_beneficiary_status (appid, beneficiary_id, status),
  KEY idx_commissions_buyer (appid, buyer_id),
  CONSTRAINT fk_commissions_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_commissions_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES users(id),
  CONSTRAINT fk_commissions_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS withdrawals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appid VARCHAR(32) NOT NULL DEFAULT '',
  user_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  status ENUM('pending','approved','rejected','paidout') NOT NULL DEFAULT 'pending',
  note VARCHAR(120) NOT NULL DEFAULT '',
  review_note VARCHAR(160) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_withdrawals_user_status (appid, user_id, status),
  KEY idx_withdrawals_status_created (appid, status, created_at),
  CONSTRAINT fk_withdrawals_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO app_settings (id, commission_level_1, commission_level_2, min_withdrawal, compliance_name, auto_pay_enabled)
VALUES (1, 0.1200, 0.0500, 10.00, '推荐有礼', 0)
ON DUPLICATE KEY UPDATE id = id;
